### ISSUE TITLE
Issue installing

### ISSUE THREAD

**Issue by Fonz29** [WantClue/Pisces-scripts#2]
Hello Wantclue. First of all thank you for your job!
Then, I had a problem installing the pisces scripts.
I have 
Module: Install ThingsIX
================================================================
Directory exists
docker: Error response from daemon: Conflict. The container name "/gwmp-mux" is                                                                              already in use by container "e597c73245f70f89ab914777a9eb96d93e15455efec84803ab1                                                                             a0501d9b27146". You have to remove (or rename) that container to be able to reus                                                                             e that name.
See 'docker run --help'.
docker: Error response from daemon: Conflict. The container name "/thingsix-forw                                                                             arder" is already in use by container "f9405b0d2de59ef4d74ae19cb538c6ce62d0797dd                                                                             ace6b0c9ee1420f6b167662". You have to remove (or rename) that container to be ab                                                                             le to reuse that name.
See 'docker run --help'.

I'm not good at coding.
Could you explain my problem and what I have to do ? And if possible the command lines ? 
Thank you !

**Comment by WantClue** [comment]
Solved everything is fixxed
